campaign:
  name: 'DEV_MediaEvalPersonDiscovery2016'
  slots:
    - slot: primary
      type: mandatory
    - slot: contrastive 1
      type: optional
    - slot: contrastive 2
      type: optional
    - slot: contrastive 3
      type: optional
    - slot: contrastive 4
      type: optional

camomile:
  host: http://camomile.mediaeval.niderb.fr
  port: 80
  username: dev_mediaevalpersondiscovery2016
  password: TxoS6pTZgJSf

annotation:
  evidence:
    queue:
      todo: DEV_evidence.todo
      done: DEV_evidence.done
  submission:
    queue:
      todo: DEV_submission.todo
      done: DEV_submission.done