campaign:
  name: 'DEV_MediaEvalPersonDiscovery2016'
  slots:
    - slot: primary
      type: mandatory
    - slot: contrastive 1
      type: optional
    - slot: contrastive 2
      type: optional
    - slot: contrastive 3
      type: optional
    - slot: contrastive 4
      type: optional

camomile:
  host: http://m111.limsi.fr:3000
  port: 80
  username: root
  password: roO7p4s5wOrD

annotation:
  evidence:
    queue:
      todo: mediaeval.evidence.in
      done: mediaeval.evidence.out
  submission:
    queue:
      todo: DEV_submission.todo
      done: DEV_submission.done